### ISSUE TITLE
new or exisiting user option selection shortcuts 

### ISSUE THREAD

**Issue by dotwayland** [jonschipp/ISLET#45]
enable ability for users to simply 'y' or 'n' in addition to typing out full word

**Comment by jonschipp** [comment]
Complete 
https://github.com/jonschipp/ISLET/commit/80bbf465921dab81554baa5e8646beff3db794d8

**Comment by jonschipp** [comment]
Also allow [nN] for new and [eE] for existing
https://github.com/jonschipp/ISLET/commit/528241dfa886318f47be6d6450eedc18f8eccaea
