### ISSUE TITLE
Can't run make

### ISSUE THREAD

**Issue by hsingh23** [jonschipp/ISLET#65]
I'm new to docker-machine, but when I ssh in I can't run make.

I think I'll just create an ubuntu box, with the ports exposed.

**Comment by jonschipp** [comment]
Hello Harsh, I'm confused about your question. To run ISLET install the dependencies `docker-engine, make, sqlite3` on a ubuntu system and then use the make targets in the documentation available in the `README.md` file.

**Comment by hsingh23** [comment]
I'm trying this from a windows machine and docker toolbox which sets up a vm with boot2docker as the image which is pretty barebones. I don't think it has sh, make, etc. It does have the docker runtime and I think I'll just boot to the islet image on docker hub.

**Comment by jonschipp** [comment]
Oh, haven't test it like that. I believe the ISLET docker images is quite a bit out of date. Let me know if you get it working.

**Comment by jonschipp** [comment]
Not an issue with ISLET per say, closing..
