### ISSUE TITLE
network breaks

### ISSUE THREAD

**Issue by hsingh23** [jonschipp/ISLET#66]
If I have the ubuntu:latest image doing an apt-get update, and then I kill it, the next time I launch a container it is not able to connect to the network. I ran the islet install in the container version. Have you seen this?

**Comment by hsingh23** [comment]
Here is what docker inspect has to say. 

docker inspect modest_mahavira 
[
{
    "Id": "1c01fab5be6b45f6ca7689c8145d27bee3c81570d9cd6238c166ee59bb2b07e4",
    "Created": "2015-11-02T06:43:59.719321362Z",
    "Path": "/bin/bash",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 7146,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-02T06:43:59.908406749Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "a5a467fddcb8848a80942d0191134c925fa16ffa9655c540acd34284f4f6375d",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "a5b7678955daa09130949da0c683c0a875d3591b11e1d395441748c35a6faa1a",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.5",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:05",
        "NetworkID": "775dd3b8dda61fcdc2112ab6f5457715ba9dd869558bbca7c46668b08e8cc069",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/1c01fab5be6b",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/1c01fab5be6b45f6ca7689c8145d27bee3c81570d9cd6238c166ee59bb2b07e4/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/1c01fab5be6b45f6ca7689c8145d27bee3c81570d9cd6238c166ee59bb2b07e4/hostname",
    "HostsPath": "/var/lib/docker/containers/1c01fab5be6b45f6ca7689c8145d27bee3c81570d9cd6238c166ee59bb2b07e4/hosts",
    "LogPath": "/var/lib/docker/containers/1c01fab5be6b45f6ca7689c8145d27bee3c81570d9cd6238c166ee59bb2b07e4/1c01fab5be6b45f6ca7689c8145d27bee3c81570d9cd6238c166ee59bb2b07e4-json.log",
    "Name": "/modest_mahavira",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [],
    "Config": {
        "Hostname": "1c01fab5be6b",
        "Domainname": "",
        "User": "",
        "AttachStdin": true,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": true,
        "Env": null,
        "Cmd": [
            "/bin/bash"
        ],
        "Image": "ubuntu:14.04.3",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by hsingh23** [comment]
after doing a service docker restart, networking works again

➜  ~  docker inspect cocky_goodall
[
{
    "Id": "853b1a89a730a94b5747a6d7508cd52ba6d32b8ac4ce597e3158cc6d36a345a9",
    "Created": "2015-11-02T06:47:03.877999386Z",
    "Path": "/bin/bash",
    "Args": [],
    "State": {
        "Running": true,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 8085,
        "ExitCode": 0,
        "Error": "",
        "StartedAt": "2015-11-02T06:47:04.064483179Z",
        "FinishedAt": "0001-01-01T00:00:00Z"
    },
    "Image": "a5a467fddcb8848a80942d0191134c925fa16ffa9655c540acd34284f4f6375d",
    "NetworkSettings": {
        "Bridge": "",
        "EndpointID": "83b387a7cb3c93ab67090760a3b794ded097d15aac329c7a462331609245204a",
        "Gateway": "172.17.42.1",
        "GlobalIPv6Address": "",
        "GlobalIPv6PrefixLen": 0,
        "HairpinMode": false,
        "IPAddress": "172.17.0.2",
        "IPPrefixLen": 16,
        "IPv6Gateway": "",
        "LinkLocalIPv6Address": "",
        "LinkLocalIPv6PrefixLen": 0,
        "MacAddress": "02:42:ac:11:00:02",
        "NetworkID": "48189f19557ab9a8075079d6f9e5e885897230513be84d02a82f30066ee27973",
        "PortMapping": null,
        "Ports": {},
        "SandboxKey": "/var/run/docker/netns/853b1a89a730",
        "SecondaryIPAddresses": null,
        "SecondaryIPv6Addresses": null
    },
    "ResolvConfPath": "/var/lib/docker/containers/853b1a89a730a94b5747a6d7508cd52ba6d32b8ac4ce597e3158cc6d36a345a9/resolv.conf",
    "HostnamePath": "/var/lib/docker/containers/853b1a89a730a94b5747a6d7508cd52ba6d32b8ac4ce597e3158cc6d36a345a9/hostname",
    "HostsPath": "/var/lib/docker/containers/853b1a89a730a94b5747a6d7508cd52ba6d32b8ac4ce597e3158cc6d36a345a9/hosts",
    "LogPath": "/var/lib/docker/containers/853b1a89a730a94b5747a6d7508cd52ba6d32b8ac4ce597e3158cc6d36a345a9/853b1a89a730a94b5747a6d7508cd52ba6d32b8ac4ce597e3158cc6d36a345a9-json.log",
    "Name": "/cocky_goodall",
    "RestartCount": 0,
    "Driver": "aufs",
    "ExecDriver": "native-0.2",
    "MountLabel": "",
    "ProcessLabel": "",
    "AppArmorProfile": "",
    "ExecIDs": null,
    "HostConfig": {
        "Binds": null,
        "ContainerIDFile": "",
        "LxcConf": [],
        "Memory": 0,
        "MemorySwap": 0,
        "CpuShares": 0,
        "CpuPeriod": 0,
        "CpusetCpus": "",
        "CpusetMems": "",
        "CpuQuota": 0,
        "BlkioWeight": 0,
        "OomKillDisable": false,
        "MemorySwappiness": -1,
        "Privileged": false,
        "PortBindings": {},
        "Links": null,
        "PublishAllPorts": false,
        "Dns": null,
        "DnsSearch": null,
        "ExtraHosts": null,
        "VolumesFrom": null,
        "Devices": [],
        "NetworkMode": "default",
        "IpcMode": "",
        "PidMode": "",
        "UTSMode": "",
        "CapAdd": null,
        "CapDrop": null,
        "GroupAdd": null,
        "RestartPolicy": {
            "Name": "no",
            "MaximumRetryCount": 0
        },
        "SecurityOpt": null,
        "ReadonlyRootfs": false,
        "Ulimits": null,
        "LogConfig": {
            "Type": "json-file",
            "Config": {}
        },
        "CgroupParent": "",
        "ConsoleSize": [
            0,
            0
        ]
    },
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    },
    "Mounts": [],
    "Config": {
        "Hostname": "853b1a89a730",
        "Domainname": "",
        "User": "",
        "AttachStdin": true,
        "AttachStdout": true,
        "AttachStderr": true,
        "ExposedPorts": null,
        "PublishService": "",
        "Tty": true,
        "OpenStdin": true,
        "StdinOnce": true,
        "Env": null,
        "Cmd": [
            "/bin/bash"
        ],
        "Image": "ubuntu:14.04.3",
        "Volumes": null,
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": null,
        "Labels": {}
    }
}
]

**Comment by hsingh23** [comment]
I think it might be this: https://github.com/docker/docker/issues/541

**Comment by jonschipp** [comment]
Okay, thanks for sharing - going to close as it looks like a Docker issue.
